# Generated by Django 5.2 on 2025-04-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='topicitem',
            table='topics',
        ),
    ]
