from django.urls import path, re_path, include
from .views import GroupedItemsView, ItemDetailView, RandomItemsView, AllItemsView

# Import Swagger modules:
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# Configure the schema view:
schema_view = get_schema_view(
    openapi.Info(
        title="Topic Classifier API",
        default_version='v1',
        description="API for querying topics generated by the topic classifier.",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Your API endpoints:
    path('api/groups/<str:group_field>/<str:group_value>/', GroupedItemsView.as_view(), name='grouped_items'),
    path('api/items/<int:id>/', ItemDetailView.as_view(), name='item_detail'),
    path('api/random/', RandomItemsView.as_view(), name='random_items'),
    path('api/items/', AllItemsView.as_view(), name='all_items'),

    # Swagger endpoints:
    # Serve JSON or YAML schema at /swagger.json or /swagger.yaml:
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # Swagger UI at /swagger/:
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # ReDoc UI at /redoc/:
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
